@id = 91faaf14-771d-4633-af3d-a2c34792cd6d
@actionId =e748b738-ffea-4c1a-9597-7dc00db901ca

### List batteries
GET {{$dotenv %baseUrl}}/batteries
Authorization: Bearer {{token}}
Content-Type: application/json

### Get battery
GET {{$dotenv %baseUrl}}/batteries/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Set operation mode
POST {{$dotenv %baseUrl}}/batteries/{{id}}/operation-mode
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "operationMode": "SELF_RELIANCE"
}

### Get operation mode action
GET {{$dotenv %baseUrl}}/batteries/actions/{{actionId}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Refresh hint
POST {{$dotenv %baseUrl}}/batteries/{{id}}/refresh-hint
Authorization: Bearer {{token}}
Content-Type: application/json