@id = 88e21125-b29c-417b-8646-3ccb662bd84e
@year = 2025
@month = 5
@day = 15


### List inverters
GET {{$dotenv %baseUrl}}/inverters
Authorization: Bearer {{token}}
Content-Type: application/json


### Get inverter
GET {{$dotenv %baseUrl}}/inverters/{{§id}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Get inverter statistics (DAY)
GET {{$dotenv %baseUrl}}/inverters/{{id}}/statistics
    ?year={{year}}
    &month={{month}}
    &day={{day}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Get inverter statistics (MONTH)
GET {{$dotenv %baseUrl}}/inverters/{{id}}/statistics
    ?year={{year}}
    &month={{month}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Refresh hint
POST {{$dotenv %baseUrl}}/batteries/{{id}}/refresh-hint
Authorization: Bearer {{token}}
Content-Type: application/json